spring.application.name=resume-analyzer

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

anthropic.api.key=${ANTHROPIC_API_KEY}
jwt.secret=${JWT_SECRET}