spring.application.name=resume-analyzer

spring.datasource.url=jdbc:postgresql://localhost:5432/resume_analyzer
spring.datasource.username=mc37
spring.datasource.password=8121960023@Aa
spring.jpa.hibernate.ddl-auto=update